services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=qwerty"
      - "POSTGRES_DB=pv311_web_api"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - "api_nt"

  api:
    image: potapchuk22/pv311_api
    networks:
      - "api_nt"
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy

networks:
  api_nt: